# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrumVoter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScrumVoter

  target 'ScrumVoterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Socket.IO-Client-Swift', '~> 8.3.3' # Or latest version

end
